### PR TITLE
fix(npm): optionally skip postinstall download of maxmind free db

### PR DESCRIPTION
**Pull request by jrgm**
Provide a way to skip this download, which isn't always the right thing to do.

r? - @vladikoff

### CODE REVIEW

**Comment by pdehaan** [comment]
Sorry, I'm just a casual observer in this repo, but does production use `postinstall`, or is that only for local development?

Should we just delete `"postinstall": "node scripts/start-db-download.js"`?
Or move it from `postinstall` to something like `download-db`; that way the database isn't downloaded automatically, but is easy enough for local developers to run `$ npm run download-db` if they need a local maxmind database?

**Comment by vladikoff** [comment]
"does production use postinstall" 

it probably should to make it simpler, but we can add a run script if @jrgm needs it 👍

**Comment by jrgm** [comment]
The production build runs the postinstall (via `npm install`), but I just don't want to bother with that in the build. The data will be more comprehensive and uptodate rpms.

**Comment by jrgm** [comment]
Hey, @vladikoff. Can you publish a new npm version?

**Pull request merged**
